name: "💡 Feature Request"
description: Create a new ticket for a new feature request
title: "💡 [REQUEST] - <title>"
labels: [
  "question"
]
body:
  - type: textarea
    id: mods
    attributes:
      label: "Mod/mods to add"
      description: Which mod/mods do you wanna request to be added to the modpack?
      placeholder: Fabric API, Sodium etc. etc.
    validations:
      required: true
  - type: textarea
    id: meaning
    attributes:
      label: "What does the mod do ?"
      description: What does this mod change?
      placeholder: Makes chunk loading faster etc. etc.
    validations:
      required: true
